/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Microsoft.Presidio.Client;
using Microsoft.Presidio.Model;

namespace Microsoft.Presidio.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDeanonymizeApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Deanonymize Text
        /// </summary>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deanonymizeRequest"></param>
        /// <returns>DeanonymizeResponse</returns>
        DeanonymizeResponse DeanonymizePost(DeanonymizeRequest deanonymizeRequest);

        /// <summary>
        /// Deanonymize Text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deanonymizeRequest"></param>
        /// <returns>ApiResponse of DeanonymizeResponse</returns>
        ApiResponse<DeanonymizeResponse> DeanonymizePostWithHttpInfo(DeanonymizeRequest deanonymizeRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDeanonymizeApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Deanonymize Text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deanonymizeRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeanonymizeResponse</returns>
        System.Threading.Tasks.Task<DeanonymizeResponse> DeanonymizePostAsync(DeanonymizeRequest deanonymizeRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Deanonymize Text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deanonymizeRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeanonymizeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeanonymizeResponse>> DeanonymizePostWithHttpInfoAsync(DeanonymizeRequest deanonymizeRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDeanonymizeApi : IDeanonymizeApiSync, IDeanonymizeApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DeanonymizeApi : IDeanonymizeApi
    {
        private Microsoft.Presidio.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DeanonymizeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DeanonymizeApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeanonymizeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DeanonymizeApi(String basePath)
        {
            this.Configuration = Microsoft.Presidio.Client.Configuration.MergeConfigurations(
                Microsoft.Presidio.Client.GlobalConfiguration.Instance,
                new Microsoft.Presidio.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Microsoft.Presidio.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Microsoft.Presidio.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Microsoft.Presidio.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeanonymizeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DeanonymizeApi(Microsoft.Presidio.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Microsoft.Presidio.Client.Configuration.MergeConfigurations(
                Microsoft.Presidio.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Microsoft.Presidio.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Microsoft.Presidio.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Microsoft.Presidio.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeanonymizeApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DeanonymizeApi(Microsoft.Presidio.Client.ISynchronousClient client, Microsoft.Presidio.Client.IAsynchronousClient asyncClient, Microsoft.Presidio.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Microsoft.Presidio.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Microsoft.Presidio.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Microsoft.Presidio.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Microsoft.Presidio.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Microsoft.Presidio.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Deanonymize Text 
        /// </summary>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deanonymizeRequest"></param>
        /// <returns>DeanonymizeResponse</returns>
        public DeanonymizeResponse DeanonymizePost(DeanonymizeRequest deanonymizeRequest)
        {
            Microsoft.Presidio.Client.ApiResponse<DeanonymizeResponse> localVarResponse = DeanonymizePostWithHttpInfo(deanonymizeRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Deanonymize Text 
        /// </summary>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deanonymizeRequest"></param>
        /// <returns>ApiResponse of DeanonymizeResponse</returns>
        public Microsoft.Presidio.Client.ApiResponse<DeanonymizeResponse> DeanonymizePostWithHttpInfo(DeanonymizeRequest deanonymizeRequest)
        {
            // verify the required parameter 'deanonymizeRequest' is set
            if (deanonymizeRequest == null)
                throw new Microsoft.Presidio.Client.ApiException(400, "Missing required parameter 'deanonymizeRequest' when calling DeanonymizeApi->DeanonymizePost");

            Microsoft.Presidio.Client.RequestOptions localVarRequestOptions = new Microsoft.Presidio.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Microsoft.Presidio.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Microsoft.Presidio.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = deanonymizeRequest;


            // make the HTTP request
            var localVarResponse = this.Client.Post<DeanonymizeResponse>("/deanonymize", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeanonymizePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Deanonymize Text 
        /// </summary>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deanonymizeRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeanonymizeResponse</returns>
        public async System.Threading.Tasks.Task<DeanonymizeResponse> DeanonymizePostAsync(DeanonymizeRequest deanonymizeRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Presidio.Client.ApiResponse<DeanonymizeResponse> localVarResponse = await DeanonymizePostWithHttpInfoAsync(deanonymizeRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Deanonymize Text 
        /// </summary>
        /// <exception cref="Microsoft.Presidio.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deanonymizeRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeanonymizeResponse)</returns>
        public async System.Threading.Tasks.Task<Microsoft.Presidio.Client.ApiResponse<DeanonymizeResponse>> DeanonymizePostWithHttpInfoAsync(DeanonymizeRequest deanonymizeRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'deanonymizeRequest' is set
            if (deanonymizeRequest == null)
                throw new Microsoft.Presidio.Client.ApiException(400, "Missing required parameter 'deanonymizeRequest' when calling DeanonymizeApi->DeanonymizePost");


            Microsoft.Presidio.Client.RequestOptions localVarRequestOptions = new Microsoft.Presidio.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Microsoft.Presidio.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Microsoft.Presidio.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = deanonymizeRequest;


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<DeanonymizeResponse>("/deanonymize", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeanonymizePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
