[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.6"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.6.2"

[prune]
  go-tests = true
  unused-packages = true
