/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Microsoft.Presidio.Client.OpenAPIDateConverter;

namespace Microsoft.Presidio.Model
{
    /// <summary>
    /// Hash
    /// </summary>
    [DataContract(Name = "Hash")]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
    public partial class Hash : Operator, IEquatable<Hash>, IValidatableObject
    {
        /// <summary>
        /// The hashing algorithm
        /// </summary>
        /// <value>The hashing algorithm</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum HashTypeEnum
        {
            /// <summary>
            /// Enum Md5 for value: md5
            /// </summary>
            [EnumMember(Value = "md5")]
            Md5 = 1,

            /// <summary>
            /// Enum Sha256 for value: sha256
            /// </summary>
            [EnumMember(Value = "sha256")]
            Sha256 = 2,

            /// <summary>
            /// Enum Sha512 for value: sha512
            /// </summary>
            [EnumMember(Value = "sha512")]
            Sha512 = 3

        }

        /// <summary>
        /// The hashing algorithm
        /// </summary>
        /// <value>The hashing algorithm</value>
        [DataMember(Name = "hash_type", EmitDefaultValue = false)]
        public HashTypeEnum? HashType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Hash" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Hash() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Hash" /> class.
        /// </summary>
        /// <param name="hashType">The hashing algorithm (default to HashTypeEnum.Md5).</param>
        /// <param name="type">type (required) (default to &quot;Hash&quot;).</param>
        public Hash(HashTypeEnum? hashType = HashTypeEnum.Md5, string type = "Hash") : base(type)
        {
            this.HashType = hashType;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Hash {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  HashType: ").Append(HashType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Hash);
        }

        /// <summary>
        /// Returns true if Hash instances are equal
        /// </summary>
        /// <param name="input">Instance of Hash to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Hash input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.HashType == input.HashType ||
                    this.HashType.Equals(input.HashType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                hashCode = hashCode * 59 + this.HashType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
