FROM python:3.9-slim

ENV PIP_NO_CACHE_DIR=1
ENV ANALYZER_CONF_FILE=presidio_analyzer/conf/default_analyzer.yaml
ENV RECOGNIZER_REGISTRY_CONF_FILE=presidio_analyzer/conf/default_recognizers.yaml
ENV NLP_CONF_FILE=presidio_analyzer/conf/transformers.yaml
ENV DEV_MODE="transformers"

# Install essential build tools
RUN apt-get update \
  && apt-get install -y build-essential

RUN pip install poetry