sudo: required
services:
  - docker
branches:
  only:
  - gh-pages
  - /.*/
matrix:
  include:
    - language: python
      cache: pip
      python:
        - "3.6"
      install:
      - travis_wait pip install -r presidio-analyzer/requirements.txt
      script:
      - make python-test
    - language: go
      go:
      - "1.10"
      go_import_path: github.com/Microsoft/presidio
      env:
      - DEP_VERSION="0.4.1"
      before_install:
      # Install kafka lib
      - git clone https://github.com/edenhill/librdkafka.git
      - cd librdkafka
      - ./configure --prefix /usr
      - make
      - sudo make install
      - cd ..
      # Download dep to bin folder in $GOPATH
      - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
       # Make dep executable
      - chmod +x $GOPATH/bin/dep
      - go get github.com/pkg/errors
      - dep ensure
      # Install gometalinter
      - go get -u github.com/alecthomas/gometalinter
      - gometalinter --install
      script:
      - make go-test
      - make test-functional
