sudo: required
services:
  - docker
branches:
  only:
  - gh-pages
  - /.*/
matrix:
  include:
    - language: python
      cache: pip
      python:
        - "3.6"
      install:
      - pip install -r presidium-analyzer/requirements.txt
      script:
      - cd presidium-analyzer
      - pytest
    - language: go
      go:
      - "1.10"
      go_import_path: github.com/presidium-io/presidium
      before_install:
      - go get github.com/pkg/errors
      script:
      - make test
      - make docker-build
