ARG REGISTRY=presidio.azurecr.io

FROM ${REGISTRY}/presidio-golang-deps

WORKDIR $GOPATH/src/github.com/Microsoft/presidio
ADD . $GOPATH/src/github.com/Microsoft/presidio

RUN dep ensure
RUN make go-test
