ARG REGISTRY=presidio.azurecr.io
ARG PRESIDIO_DEPS_LABEL=latest

FROM ${REGISTRY}/presidio-golang-deps:${PRESIDIO_DEPS_LABEL}


COPY Gopkg.lock Gopkg.toml $GOPATH/src/github.com/Microsoft/presidio/
WORKDIR $GOPATH/src/github.com/Microsoft/presidio
RUN dep ensure -vendor-only

ADD . $GOPATH/src/github.com/Microsoft/presidio
RUN make go-test