services:
  presidio-anonymizer:
    image: ghcr.io/data-privacy-stack/presidio-anonymizer:latest
    build:
      context: ./presidio-anonymizer
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
  presidio-analyzer:
    image: ghcr.io/data-privacy-stack/presidio-analyzer:latest
    build:
      context: ./presidio-analyzer
    environment:
      - PORT=5001
    ports:
      - "5002:5001"
