services:
  presidio-image-redactor:
    image: ghcr.io/data-privacy-stack/presidio-image-redactor:latest
    build:
      context: ./presidio-image-redactor
    environment:
      - PORT=5001
    ports:
      - "5003:5001"
