services:
  presidio-image-redactor:
    image: ${REGISTRY_NAME:-ghcr.io/data-privacy-stack}/${IMAGE_PREFIX:-}presidio-image-redactor${TAG:-:latest}
    build:
      context: ./presidio-image-redactor
    environment:
      - PORT=5001
    ports:
      - "5003:5001"
