version: '3.4'
services:
  presidio-golang-deps:
    image: ${REPOSITORY_URI}/presidio-golang-deps:${DOCKER_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile.golang.deps
      cache_from:
        - ${REPOSITORY_URI}/presidio-golang-deps:${DOCKER_TAG}
  presidio-golang-base:
    image: ${REPOSITORY_URI}/presidio-golang-base:${DOCKER_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile.golang.base
      args:
        - REGISTRY: 289208114389.dkr.ecr.us-east-1.amazonaws.com/picpay-dev
        - PRESIDIO_DEPS_LABEL: latest
      cache_from:
        - ${REPOSITORY_URI}/presidio-golang-base:${DOCKER_TAG}
  presidio-python-deps:
    image: ${REPOSITORY_URI}/presidio-python-deps:${DOCKER_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile.python.deps
      cache_from:
        - ${REPOSITORY_URI}/presidio-python-deps:${DOCKER_TAG}
  presidio-analyzer:
    image: ${REPOSITORY_URI}/presidio-analyzer:${DOCKER_TAG}
    build:
      context: .
      dockerfile: ./presidio-analyzer/Dockerfile
      cache_from:
        - ${REPOSITORY_URI}/presidio-analyzer:${DOCKER_TAG}
  presidio-anonymizer:
    image: ${REPOSITORY_URI}/presidio-anonymizer:${DOCKER_TAG}
    build:
      context: .
      dockerfile: ./presidio-anonymizer/Dockerfile
      cache_from:
        - ${REPOSITORY_URI}/presidio-anonymizer:${DOCKER_TAG}
  presidio-recognizers-store:
    image: ${REPOSITORY_URI}/presidio-recognizers-store:${DOCKER_TAG}
    build:
      context: .
      dockerfile: ./presidio-recognizers-store/Dockerfile
      cache_from:
        - ${REPOSITORY_URI}/presidio-recognizers-store:${DOCKER_TAG}
  presidio-api:
    image: ${REPOSITORY_URI}/presidio-api:${DOCKER_TAG}
    build:
      context: .
      dockerfile: ./presidio-api/Dockerfile
      cache_from:
        - ${REPOSITORY_URI}/presidio-api:${DOCKER_TAG}
  presidio-datasink:
    image: ${REPOSITORY_URI}/presidio-datasink:${DOCKER_TAG}
    build:
      context: .
      dockerfile: ./presidio-datasink/Dockerfile
      cache_from:
        - ${REPOSITORY_URI}/presidio-datasink:${DOCKER_TAG}
  presidio-ocr:
    image: ${REPOSITORY_URI}/presidio-ocr:${DOCKER_TAG}
    build:
      context: .
      dockerfile: ./presidio-ocr/Dockerfile
      cache_from:
        - ${REPOSITORY_URI}/presidio-ocr:${DOCKER_TAG}
  presidio-collector:
    image: ${REPOSITORY_URI}/presidio-collector:${DOCKER_TAG}
    build:
      context: .
      dockerfile: ./presidio-collector/Dockerfile
      cache_from:
        - ${REPOSITORY_URI}/presidio-collector:${DOCKER_TAG}
