services:
  presidio-anonymizer:
    image: ${REGISTRY_NAME:-ghcr.io/data-privacy-stack}/${IMAGE_PREFIX:-}presidio-anonymizer${TAG:-:latest}
    build:
      context: ./presidio-anonymizer
    environment:
      - PORT=5001
    ports:
      - "5001:5001"
  presidio-analyzer:
    image: ${REGISTRY_NAME:-ghcr.io/data-privacy-stack}/${IMAGE_PREFIX:-}presidio-analyzer${TAG:-:latest}
    build:
      context: ./presidio-analyzer
    environment:
      - PORT=5001
    ports:
      - "5002:5001"
