ARG REGISTRY=presidio.azurecr.io
ARG PRESIDIO_DEPS_LABEL=latest

FROM ${REGISTRY}/presidio-golang-deps:${PRESIDIO_DEPS_LABEL}

WORKDIR $GOPATH/src/github.com/Microsoft/presidio
ADD Gopkg.* $GOPATH/src/github.com/Microsoft/presidio/
RUN dep ensure --vendor-only
ADD . $GOPATH/src/github.com/Microsoft/presidio

RUN make go-test