apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "presidio.ingress.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "presidio.api.fullname" . }}
          servicePort: {{ .Values.api.service.externalPort }}