{{- if and (.Values.api.ingress.enabled) (or (eq .Values.api.ingress.class "nginx") (eq .Values.api.ingress.class "traefik")) -}}
{{- $serviceName := include "presidio.api.fullname" . -}}
{{- $servicePort := .Values.api.service.externalPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.api.ingress.class }}
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ $serviceName }}
          servicePort: {{ $servicePort }}
{{- end -}}
