{{ $fullname := include "presidio.scheduler.fullname" . }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      serviceAccountName: {{ $fullname }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.scheduler.name }}:{{ default .Chart.AppVersion .Values.scheduler.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.scheduler.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.scheduler.service.internalPort }}
        env:
          - name: PRESIDIO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GRPC_PORT
            value: {{ .Values.scheduler.service.internalPort | quote }}
          - name: REDIS_URL
            value: {{ .Values.redis.url}}
          - name: ANALYZER_SVC_ADDRESS
            value:  {{ template "presidio.analyzer.address" . }}
          - name: ANONYMIZER_SVC_ADDRESS
            value:  {{ template "presidio.anonymizer.address" . }}
          - name: DATASINK_GRPC_PORT
            value: "5000"
          - name: DATASINK_IMAGE_NAME
            value: {{ .Values.registry }}/{{ .Values.datasink.name }}:{{ default .Chart.AppVersion .Values.datasink.tag }}
          - name: DATASINK_PULL_POLICY
            value: {{ default "IfNotPresent" .Values.datasink.imagePullPolicy }}
          - name: COLLECTOR_IMAGE_NAME
            value: {{ .Values.registry }}/{{ .Values.collector.name }}:{{ default .Chart.AppVersion .Values.collector.tag }}
          - name: COLLECTOR_IMAGE_PULL_POLICY
            value: {{ default "IfNotPresent" .Values.collector.imagePullPolicy }}
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}