{{ $fullname := include "presidio.scheduler.fullname" . }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      serviceAccountName: {{ $fullname }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.scheduler.name }}:{{ default .Chart.AppVersion .Values.scheduler.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.scheduler.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.scheduler.service.internalPort }}
        env:
          - name: presidio_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GRPC_PORT
            value: {{ .Values.scheduler.service.internalPort | quote }}
          - name: REDIS_HOST
            value: {{ .Values.redis.host}}
          - name: REDIS_PORT
            value: {{ .Values.redis.port | quote }}
          - name: ANALYZER_SVC_HOST
            value:  {{ template "presidio.analyzer.fullname" . }}
          - name: ANALYZER_SVC_PORT
            value: {{ .Values.analyzer.service.externalPort | quote }}
          - name: DATABINDER_IMAGE_NAME
            value: {{ .Values.registry }}/{{ .Values.databinder.name }}:{{ default .Chart.AppVersion .Values.databinder.tag }}
          - name: SCANNER_IMAGE_NAME
            value: {{ .Values.registry }}/{{ .Values.scanner.name }}:{{ default .Chart.AppVersion .Values.scanner.tag }}
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}