{{ $fullname := include "presidio.scheduler.fullname" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    service: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
  - port: {{ .Values.scheduler.service.externalPort }}
    targetPort: {{ .Values.scheduler.service.internalPort }}
    protocol: TCP
    name: {{ .Values.scheduler.service.name }}
  selector:
    app: {{ $fullname }}