{{ $fullname := include "presidio.scheduler.fullname" . }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    app: {{ $fullname }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      serviceAccountName: {{ $fullname }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry }}/{{ .Values.scheduler.name }}:{{ default .Chart.AppVersion .Values.scheduler.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.scheduler.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.scheduler.service.internalPort }}
        env:
          - name: presidio_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GRPC_PORT
            value: {{ .Values.scheduler.service.internalPort | quote }}
          - name: REDIS_URL
            value: "{{ .Values.redis.host}}:{{ .Values.redis.port | quote }}"
          - name: ANALYZER_SVC_ADDRESS
            value:  "{{ template "presidio.analyzer.fullname" . }}:{{ .Values.analyzer.service.externalPort | quote }}"
          - name: ANONYMIZER_SVC_ADDRESS
            value:  "{{ template "presidio.anonymizer.fullname" . }}:{{ .Values.anonymizer.service.externalPort | quote }}"
          - name: DATASINK_GRPC_PORT
            value: 5000
          - name: DATASINK_IMAGE_NAME
            value: {{ .Values.registry }}/{{ .Values.datasink.name }}:{{ default .Chart.AppVersion .Values.datasink.tag }}
          - name: SCANNER_IMAGE_NAME
            value: {{ .Values.registry }}/{{ .Values.scanner.name }}:{{ default .Chart.AppVersion .Values.scanner.tag }}
          - name: SCANNER_IMAGE_PULL_POLICY
            value: {{ default "IfNotPresent" .Values.scanner.imagePullPolicy }}
          - name: STREAMS_IMAGE_NAME
            value: {{ .Values.registry }}/{{ .Values.streams.name }}:{{ default .Chart.AppVersion .Values.streams.tag }}
          - name: STREAMS_IMAGE_PULL_POLICY
            value: {{ default "IfNotPresent" .Values.streams.imagePullPolicy }}
          - name: DATASINK_PULL_POLICY
            value: {{ default "IfNotPresent" .Values.datasink.imagePullPolicy }}
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}