# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='types',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x05types\"\x91\x01\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\t\x12\x11\n\tfieldType\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\x02\x12!\n\x08location\x18\x04 \x01(\x0b\x32\x0f.types.Location\x12-\n\x0etransformation\x18\x05 \x01(\x0b\x32\x15.types.Transformation\"k\n\x08Location\x12\r\n\x05start\x18\x01 \x01(\x11\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x11\x12\x0e\n\x06length\x18\x03 \x01(\x11\x12\x10\n\x08newStart\x18\x04 \x01(\x11\x12\x0e\n\x06newEnd\x18\x05 \x01(\x11\x12\x11\n\tnewLength\x18\x06 \x01(\x11\"v\n\x0eTransformation\x12\x10\n\x08newValue\x18\x01 \x01(\t\x12)\n\x0creplaceValue\x18\x02 \x01(\x0b\x32\x13.types.ReplaceValue\x12\'\n\x0bredactValue\x18\x03 \x01(\x0b\x32\x12.types.RedactValue\" \n\x0cReplaceValue\x12\x10\n\x08newValue\x18\x01 \x01(\t\"\r\n\x0bRedactValue\"\x16\n\x14RecordTransformationb\x06proto3')
)




_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='types.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='types.Result.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fieldType', full_name='types.Result.fieldType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probability', full_name='types.Result.probability', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='types.Result.location', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transformation', full_name='types.Result.transformation', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=169,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='types.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='types.Location.start', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='types.Location.end', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='types.Location.length', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newStart', full_name='types.Location.newStart', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newEnd', full_name='types.Location.newEnd', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newLength', full_name='types.Location.newLength', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=278,
)


_TRANSFORMATION = _descriptor.Descriptor(
  name='Transformation',
  full_name='types.Transformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newValue', full_name='types.Transformation.newValue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='replaceValue', full_name='types.Transformation.replaceValue', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='redactValue', full_name='types.Transformation.redactValue', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=398,
)


_REPLACEVALUE = _descriptor.Descriptor(
  name='ReplaceValue',
  full_name='types.ReplaceValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='newValue', full_name='types.ReplaceValue.newValue', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=432,
)


_REDACTVALUE = _descriptor.Descriptor(
  name='RedactValue',
  full_name='types.RedactValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=447,
)


_RECORDTRANSFORMATION = _descriptor.Descriptor(
  name='RecordTransformation',
  full_name='types.RecordTransformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=471,
)

_RESULT.fields_by_name['location'].message_type = _LOCATION
_RESULT.fields_by_name['transformation'].message_type = _TRANSFORMATION
_TRANSFORMATION.fields_by_name['replaceValue'].message_type = _REPLACEVALUE
_TRANSFORMATION.fields_by_name['redactValue'].message_type = _REDACTVALUE
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['Transformation'] = _TRANSFORMATION
DESCRIPTOR.message_types_by_name['ReplaceValue'] = _REPLACEVALUE
DESCRIPTOR.message_types_by_name['RedactValue'] = _REDACTVALUE
DESCRIPTOR.message_types_by_name['RecordTransformation'] = _RECORDTRANSFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:types.Result)
  ))
_sym_db.RegisterMessage(Result)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:types.Location)
  ))
_sym_db.RegisterMessage(Location)

Transformation = _reflection.GeneratedProtocolMessageType('Transformation', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFORMATION,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:types.Transformation)
  ))
_sym_db.RegisterMessage(Transformation)

ReplaceValue = _reflection.GeneratedProtocolMessageType('ReplaceValue', (_message.Message,), dict(
  DESCRIPTOR = _REPLACEVALUE,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:types.ReplaceValue)
  ))
_sym_db.RegisterMessage(ReplaceValue)

RedactValue = _reflection.GeneratedProtocolMessageType('RedactValue', (_message.Message,), dict(
  DESCRIPTOR = _REDACTVALUE,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:types.RedactValue)
  ))
_sym_db.RegisterMessage(RedactValue)

RecordTransformation = _reflection.GeneratedProtocolMessageType('RecordTransformation', (_message.Message,), dict(
  DESCRIPTOR = _RECORDTRANSFORMATION,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:types.RecordTransformation)
  ))
_sym_db.RegisterMessage(RecordTransformation)


# @@protoc_insertion_point(module_scope)
