rbac:
  enabled: false

consul:
  service: consul.presidium-system.svc.cluster.local:8500

ingress:
  class: traefik

api:
  registry: presidiumio
  name: presidium-api
  # tag:
  service:
    type: ClusterIP
    externalPort: 8080
    internalPort: 8080
  # Configure liveness probes except `httpGet` and the belongings
  #livenessProbe:
  #  initialDelaySeconds: 20
  # Configure readiness probes except `httpGet` and the belongings
  #readinessProbe:
  #  initialDelaySeconds: 20

registrator:
  registry: presidiumio
  name: presidium-registrator
  # tag:
  imagePullPolicy: Always
  redis:
    host: redis-master
    port: 6379

analyzer:
  registry: presidiumio
  name: presidium-analyzer
  # tag:
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

anonymizer:
  registry: presidiumio
  name: presidium-anonymizer
  # tag:
  imagePullPolicy: Always
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001

scheduler:
  registry: presidiumio
  name: presidium-scheduler
  imagePullPolicy: Always
  # tag:
  service:
    type: ClusterIP
    externalPort: 3001
    internalPort: 3001