version: 2
jobs:
  build:
    branches:
      only:
        - gh-pages
        - /.*/
    
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "presidio-analyzer/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r presidio-analyzer/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "presidio-analyzer/requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make python-test