/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Presidio.Client.OpenAPIDateConverter;

namespace Presidio.Model
{
    /// <summary>
    /// RecognizerResultWithAnalysis
    /// </summary>
    [DataContract(Name = "RecognizerResultWithAnalysis")]
    [JsonConverter(typeof(JsonSubtypes), "RecognizerResultWithAnalysis")]
    [JsonSubtypes.KnownSubType(typeof(RecognizerResultWithAnalysis), "RecognizerResultWithAnalysis")]
    public partial class RecognizerResultWithAnalysis : RecognizerResult, IEquatable<RecognizerResultWithAnalysis>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecognizerResultWithAnalysis" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecognizerResultWithAnalysis() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecognizerResultWithAnalysis" /> class.
        /// </summary>
        /// <param name="analysisExplanation">analysisExplanation.</param>
        /// <param name="start">Where the PII starts (required).</param>
        /// <param name="end">Where the PII ends (required).</param>
        /// <param name="score">The PII detection score (required).</param>
        /// <param name="entityType">The supported PII entity types. (required).</param>
        public RecognizerResultWithAnalysis(AnalysisExplanation analysisExplanation = default(AnalysisExplanation), int start = default(int), int end = default(int), double score = default(double), string entityType = default(string)) : base(start, end, score, entityType)
        {
            this.AnalysisExplanation = analysisExplanation;
        }

        /// <summary>
        /// Gets or Sets AnalysisExplanation
        /// </summary>
        [DataMember(Name = "analysis_explanation", EmitDefaultValue = false)]
        public AnalysisExplanation AnalysisExplanation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RecognizerResultWithAnalysis {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  AnalysisExplanation: ").Append(AnalysisExplanation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RecognizerResultWithAnalysis);
        }

        /// <summary>
        /// Returns true if RecognizerResultWithAnalysis instances are equal
        /// </summary>
        /// <param name="input">Instance of RecognizerResultWithAnalysis to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RecognizerResultWithAnalysis input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.AnalysisExplanation == input.AnalysisExplanation ||
                    (this.AnalysisExplanation != null &&
                    this.AnalysisExplanation.Equals(input.AnalysisExplanation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.AnalysisExplanation != null)
                    hashCode = hashCode * 59 + this.AnalysisExplanation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
