/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Presidio.Client.OpenAPIDateConverter;

namespace Presidio.Model
{
    /// <summary>
    /// RecognizerResult
    /// </summary>
    [DataContract(Name = "RecognizerResult")]
    [JsonConverter(typeof(JsonSubtypes), "RecognizerResultWithAnalysis")]
    [JsonSubtypes.KnownSubType(typeof(RecognizerResultWithAnalysis), "RecognizerResultWithAnalysis")]
    public partial class RecognizerResult : IEquatable<RecognizerResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecognizerResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RecognizerResult() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RecognizerResult" /> class.
        /// </summary>
        /// <param name="start">Where the PII starts (required).</param>
        /// <param name="end">Where the PII ends (required).</param>
        /// <param name="score">The PII detection score (required).</param>
        /// <param name="entityType">The supported PII entity types. (required).</param>
        public RecognizerResult(int start = default(int), int end = default(int), double score = default(double), string entityType = default(string))
        {
            this.Start = start;
            this.End = end;
            this.Score = score;
            // to ensure "entityType" is required (not null)
            this.EntityType = entityType ?? throw new ArgumentNullException("entityType is a required property for RecognizerResult and cannot be null");
        }

        /// <summary>
        /// Where the PII starts
        /// </summary>
        /// <value>Where the PII starts</value>
        [DataMember(Name = "start", IsRequired = true, EmitDefaultValue = false)]
        public int Start { get; set; }

        /// <summary>
        /// Where the PII ends
        /// </summary>
        /// <value>Where the PII ends</value>
        [DataMember(Name = "end", IsRequired = true, EmitDefaultValue = false)]
        public int End { get; set; }

        /// <summary>
        /// The PII detection score
        /// </summary>
        /// <value>The PII detection score</value>
        [DataMember(Name = "score", IsRequired = true, EmitDefaultValue = false)]
        public double Score { get; set; }

        /// <summary>
        /// The supported PII entity types.
        /// </summary>
        /// <value>The supported PII entity types.</value>
        [DataMember(Name = "entity_type", IsRequired = true, EmitDefaultValue = false)]
        public string EntityType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RecognizerResult {\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("  End: ").Append(End).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  EntityType: ").Append(EntityType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RecognizerResult);
        }

        /// <summary>
        /// Returns true if RecognizerResult instances are equal
        /// </summary>
        /// <param name="input">Instance of RecognizerResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RecognizerResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Start == input.Start ||
                    this.Start.Equals(input.Start)
                ) && 
                (
                    this.End == input.End ||
                    this.End.Equals(input.End)
                ) && 
                (
                    this.Score == input.Score ||
                    this.Score.Equals(input.Score)
                ) && 
                (
                    this.EntityType == input.EntityType ||
                    (this.EntityType != null &&
                    this.EntityType.Equals(input.EntityType))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Start.GetHashCode();
                hashCode = hashCode * 59 + this.End.GetHashCode();
                hashCode = hashCode * 59 + this.Score.GetHashCode();
                if (this.EntityType != null)
                    hashCode = hashCode * 59 + this.EntityType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
