/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Presidio.Api;
using Presidio.Model;
using Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Presidio.Test.Model
{
    /// <summary>
    ///  Class for testing AnonymizeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnonymizeRequestTests : IDisposable
    {

        private AnonymizeRequest instance;
        private List<RecognizerResult> results;
        private Dictionary<string, Anonymizer> anonymizers;

        public AnonymizeRequestTests()
        {
            var encrypt = new Replace("replace", "val");
            anonymizers = new Dictionary<string, Anonymizer>() {{"PERSON", new Anonymizer(encrypt)}};
            var result = new RecognizerResult(start: 11, end: 24, score: 0.9, entityType: "PERSON");
            results = new List<RecognizerResult>() {result};
            instance = new AnonymizeRequest(text: "hello world", anonymizers: anonymizers, analyzerResults: results);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnonymizeRequest
        /// </summary>
        [Fact]
        public void AnonymizeRequestInstanceTest()
        {
            Assert.IsType<AnonymizeRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
             Assert.Equal(instance.Text, "hello world");
        }
        /// <summary>
        /// Test the property 'Anonymizers'
        /// </summary>
        [Fact]
        public void AnonymizersTest()
        {
            Assert.Equal(instance.Anonymizers, anonymizers);
        }
        /// <summary>
        /// Test the property 'AnalyzerResults'
        /// </summary>
        [Fact]
        public void AnalyzerResultsTest()
        {
            Assert.Equal(instance.AnalyzerResults, results);
        }

    }

}