/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Presidio.Api;
using Presidio.Model;
using Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Presidio.Test.Model
{
    /// <summary>
    ///  Class for testing Deanonymizer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeanonymizerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Deanonymizer
        //private Deanonymizer instance;

        public DeanonymizerTests()
        {
            // TODO uncomment below to create an instance of Deanonymizer
            //instance = new Deanonymizer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Deanonymizer
        /// </summary>
        [Fact]
        public void DeanonymizerInstanceTest()
        {
            // TODO uncomment below to test "IsType" Deanonymizer
            //Assert.IsType<Deanonymizer>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

    }

}
