/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Presidio.Api;
using Presidio.Model;
using Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Presidio.Test.Model
{
    /// <summary>
    ///  Class for testing Mask
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MaskTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Mask
        //private Mask instance;

        public MaskTests()
        {
            // TODO uncomment below to create an instance of Mask
            //instance = new Mask();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Mask
        /// </summary>
        [Fact]
        public void MaskInstanceTest()
        {
            // TODO uncomment below to test "IsType" Mask
            //Assert.IsType<Mask>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'MaskingChar'
        /// </summary>
        [Fact]
        public void MaskingCharTest()
        {
            // TODO unit test for the property 'MaskingChar'
        }
        /// <summary>
        /// Test the property 'CharsToMask'
        /// </summary>
        [Fact]
        public void CharsToMaskTest()
        {
            // TODO unit test for the property 'CharsToMask'
        }
        /// <summary>
        /// Test the property 'FromEnd'
        /// </summary>
        [Fact]
        public void FromEndTest()
        {
            // TODO unit test for the property 'FromEnd'
        }

    }

}
