/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Presidio.Api;
using Presidio.Model;
using Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Presidio.Test.Model
{
    /// <summary>
    ///  Class for testing Pattern
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatternTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Pattern
        //private Pattern instance;

        public PatternTests()
        {
            // TODO uncomment below to create an instance of Pattern
            //instance = new Pattern();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Pattern
        /// </summary>
        [Fact]
        public void PatternInstanceTest()
        {
            // TODO uncomment below to test "IsType" Pattern
            //Assert.IsType<Pattern>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Regex'
        /// </summary>
        [Fact]
        public void RegexTest()
        {
            // TODO unit test for the property 'Regex'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }

    }

}
