/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Presidio.Api;
using Presidio.Model;
using Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Presidio.Test.Model
{
    /// <summary>
    ///  Class for testing RecognizerResultWithAnalysis
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecognizerResultWithAnalysisTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecognizerResultWithAnalysis
        //private RecognizerResultWithAnalysis instance;

        public RecognizerResultWithAnalysisTests()
        {
            // TODO uncomment below to create an instance of RecognizerResultWithAnalysis
            //instance = new RecognizerResultWithAnalysis();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecognizerResultWithAnalysis
        /// </summary>
        [Fact]
        public void RecognizerResultWithAnalysisInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecognizerResultWithAnalysis
            //Assert.IsType<RecognizerResultWithAnalysis>(instance);
        }


        /// <summary>
        /// Test the property 'AnalysisExplanation'
        /// </summary>
        [Fact]
        public void AnalysisExplanationTest()
        {
            // TODO unit test for the property 'AnalysisExplanation'
        }

    }

}
