# Presidio Release Docs: Push to Github Pages

trigger: none
pr: none

stages:
    - stage: Release
      displayName: Release Docs to Github Pages
      jobs:
          - job: githubPagesRelease
            displayName: Push to github pages
            steps:
                - checkout: self
                  persistCredentials: true
                - task: UsePythonVersion@0
                - script: |
                      set -eux  # fail on error                                            
                      pip install -r docs/requirements-docs.txt

                      # Install Presidio modules for generating API references
                      pip install presidio-analyzer --no-dependencies
                      pip install presidio-anonymizer --no-dependencies
                      pip install presidio-image-redactor --no-dependencies
                      mkdocs gh-deploy
