# Presidio Release Docs: Push to Github Pages

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'
stages:
    - stage: Release
      displayName: Release Docs to Github Pages
      jobs:
          - job: githubPagesRelease
            displayName: Push to github pages
            steps:
                - checkout: self
                  persistCredentials: true
                - task: UsePythonVersion@0
                - script: |
                      set -eux  # fail on error     
                      pip install --upgrade pip      
                      pip install wheel                                 
                      pip install -r docs/requirements-docs.txt
                      mkdocs gh-deploy
