# Presidio-Image-Redactor Release: pypi and to ACR twice (with verison, latest) with 'public' tag for MCR release.

trigger: none
pr: none

variables:
    - group: Presidio-V2-CI
stages:
    - stage: Release
      displayName: Release
      jobs:
          - job: version
            displayName: 'Get the version number'
            steps:
                - bash: |
                      set -eux  # exit on error
                      ver=$(cat VERSION-IMAGE-REDACTOR)
                      echo $ver
                      echo "##vso[task.setvariable variable=version;isOutput=true]$ver"
                  displayName: Set Version
                  name: setVer

          - job: PublishToPyPi
            displayName: Publish to PyPi
            dependsOn: version
            steps:
                - template: ./publish-to-pypi.yml
                  parameters:
                      WORKING_FOLDER: 'presidio-image-redactor'

          - job: BuildAndPushContainers
            displayName: Build and Push Containers
            dependsOn: version
            pool:
                vmImage: 'ubuntu-16.04'
            variables:
                version: $[ dependencies.Version.outputs['setVer.version'] ]
                REGISTRY_NAME: '$(ACR_REGISTRY_NAME).azurecr.io/'
                IMAGE_PREFIX: 'public/'
            steps:
                - template: ./build-and-push-containers.yml
                  parameters:
                      REGISTRY_NAME: $(REGISTRY_NAME)
                      IMAGE_PREFIX: $(IMAGE_PREFIX)
                      TAG: ':$(version)'
                      AZURE_SUBSCRIPTION: $(ACR_AZURE_SUBSCRIPTION)
                      DOCKER_COMPOSE_FILE: '../docker-compose-image-redactor.yml'
                - template: ./build-and-push-containers.yml
                  parameters:
                      REGISTRY_NAME: $(REGISTRY_NAME)
                      IMAGE_PREFIX: $(IMAGE_PREFIX)
                      TAG: ':latest'
                      AZURE_SUBSCRIPTION: $(ACR_AZURE_SUBSCRIPTION)  
                      DOCKER_COMPOSE_FILE: '../docker-compose-image-redactor.yml'  
