jobs:
- job: version
  displayName: 'Get the version number'
  steps:
    - bash: |
        set -eux  # exit on error
        ver=$(cat VERSION)
        echo $ver
        echo "##vso[task.setvariable variable=version;isOutput=true]$ver"
      displayName: Set Version
      name: setVer
- job: githubRelease
  displayName: GitHub Release
  dependsOn: version
  variables:
    version: $[ dependencies.Version.outputs['setVer.version'] ]
  steps:
    - task: GitHubRelease@0
      inputs:
        gitHubConnection: $(GITHUB_CONNECTION)
        tagSource: manual
        tag: $(version)
