"""Constants for GLiNER edge profile."""

GLINER_FREE_TEXT_RECOGNIZER_NAME = "GLiNERFreeTextRecognizer"
GLINER_DOB_RECOGNIZER_NAME = "GLiNERDobRecognizer"

GLINER_OWNED_ENTITIES = {"PERSON", "LOCATION", "ORGANIZATION", "DATE_TIME"}
REGEX_OWNED_ENTITIES = {"EMAIL_ADDRESS", "PHONE_NUMBER", "US_SSN", "CREDIT_CARD"}
