# Dockerfile
FROM python:3.13-slim

RUN apt-get update \
  && apt-get install -y build-essential

# Install dependencies required for Tesseract
RUN apt-get update \
  && apt-get install tesseract-ocr -y \
  && rm -rf /var/lib/apt/lists/* \
  && tesseract -v

RUN apt-get update  \
&& apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install poetry

# Create a non-root user for development
RUN useradd -m -u 1001 presidio

USER 1001
