# Dockerfile
FROM python:3.13-slim@sha256:f50f56f1471fc430b394ee75fc826be2d212e35d85ed1171ac79abbba485dce9

RUN apt-get update \
  && apt-get install -y build-essential

# Install dependencies required for Tesseract
RUN apt-get update \
  && apt-get install tesseract-ocr -y \
  && rm -rf /var/lib/apt/lists/* \
  && tesseract -v

RUN apt-get update  \
&& apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install poetry==2.3.2
