# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyze.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='analyze.proto',
  package='types',
  syntax='proto3',
  serialized_pb=_b('\n\ranalyze.proto\x12\x05types\x1a\x0c\x63ommon.proto\")\n\x07Results\x12\x1e\n\x07results\x18\x01 \x03(\x0b\x32\r.types.Result\"/\n\x0e\x41nalyzeRequest\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06\x66ields\x18\x02 \x03(\t2B\n\x0e\x41nalyzeService\x12\x30\n\x05\x41pply\x12\x15.types.AnalyzeRequest\x1a\x0e.types.Results\"\x00\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_RESULTS = _descriptor.Descriptor(
  name='Results',
  full_name='types.Results',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='types.Results.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=79,
)


_ANALYZEREQUEST = _descriptor.Descriptor(
  name='AnalyzeRequest',
  full_name='types.AnalyzeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='types.AnalyzeRequest.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='types.AnalyzeRequest.fields', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=128,
)

_RESULTS.fields_by_name['results'].message_type = common__pb2._RESULT
DESCRIPTOR.message_types_by_name['Results'] = _RESULTS
DESCRIPTOR.message_types_by_name['AnalyzeRequest'] = _ANALYZEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Results = _reflection.GeneratedProtocolMessageType('Results', (_message.Message,), dict(
  DESCRIPTOR = _RESULTS,
  __module__ = 'analyze_pb2'
  # @@protoc_insertion_point(class_scope:types.Results)
  ))
_sym_db.RegisterMessage(Results)

AnalyzeRequest = _reflection.GeneratedProtocolMessageType('AnalyzeRequest', (_message.Message,), dict(
  DESCRIPTOR = _ANALYZEREQUEST,
  __module__ = 'analyze_pb2'
  # @@protoc_insertion_point(class_scope:types.AnalyzeRequest)
  ))
_sym_db.RegisterMessage(AnalyzeRequest)



_ANALYZESERVICE = _descriptor.ServiceDescriptor(
  name='AnalyzeService',
  full_name='types.AnalyzeService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=130,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='Apply',
    full_name='types.AnalyzeService.Apply',
    index=0,
    containing_service=None,
    input_type=_ANALYZEREQUEST,
    output_type=_RESULTS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALYZESERVICE)

DESCRIPTOR.services_by_name['AnalyzeService'] = _ANALYZESERVICE

# @@protoc_insertion_point(module_scope)
