# CI pipeline for presidio. This pipeline triggers the build-test-publish template for every PR
# and merge to master on https://github.com/microsoft/presidio.
# Pipeline parameters:
#   * AZURE_ARTIFACTS_PYPI_INDEX_URL - pypi endpoint used to push the presidio analyzer wheel during CI.
#                   presidio uses internally an Azure Artifacts feed to store the built wheels.
#                   https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/python-packages?view=azure-devops
#   * AZURE_ARTIFACTS_FEED_NAME - name of Azure Artifact's pypi feed endpoint
#   * PYPI_SERVICE_CONNECTION - service connection with pypi credentials
#   * PYPI_FEED_NAME - name of service connection to pypi's feed endpoint
#   * REGISTRY - service connection to docker registry.
#   * REGISTRY_NAME - full name of container registry (i.e. presidio.azurecr.io).
#   * RELEASE_NAME - presidio release version.

variables:
- group: Presidio - CI Pipeline
- name: GOBIN
  value: '$(GOPATH)/bin'
- name: GOPATH
  value: '$(system.defaultWorkingDirectory)/gopath'
- name: MODULEPATH
  value: '$(GOPATH)/src/github.com/$(build.repository.name)'
- name: GOROOT
  value: '/usr/local/go1.11'
- name: PYTHON.VERSION
  value: '3.7'

trigger: # CI triggers	
  batch: false 
  branches:
      include: 
      - master	
  paths:
    exclude: 
      - '*.md'
pr: # PR triggers	
  branches:
      include: 
      - master
  paths:
    exclude: 
      - '*.md'
stages:
  - template: templates/build-test-publish.yaml
    parameters:
      registry_service_principal: $(REGISTRY)
      registry_name: $(REGISTRY_NAME)
      internal_pypi_feed_name: $(AZURE_ARTIFACTS_FEED_NAME)
      internal_pypi_extra_index_url: $(AZURE_ARTIFACTS_PYPI_INDEX_URL)
      external_pypi_service_conection: $(PYPI_SERVICE_CONNECTION)
      external_pypi_feed_name: $(PYPI_FEED_NAME)




