# CI pipeline for presidio. This pipeline triggers the build-test-publish template for every PR
# and merge to master on https://github.com/microsoft/presidio.
# Pipeline parameters:
#   * PYPI_INDEX_URL - pypi artifact used to push the wheel.
#   * REGISTRY - service connection to docker registry.
#   * REGISTRY_NAME - full name of container registry (i.e. presidio.azurecr.io).
#   * RELEASE_NAME - presidio release version.
variables:
  GOBIN: '$(GOPATH)/bin'
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  MODULEPATH: '$(GOPATH)/src/github.com/$(build.repository.name)'
  GOROOT: '/usr/local/go1.11'
  PYTHON.VERSION: '3.7'

trigger: # CI triggers	
  batch: false 
  branches:
      include: 
      - master	
  paths:
    exclude: 
      - '*.md'
pr: # PR triggers	
  branches:
      include: 
      - development	
  paths:
    exclude: 
      - '*.md'
stages:
  - template: templates/build-test-publish.yaml
    parameters:
      registry_service_principal: $(REGISTRY)
      registry_name: $(REGISTRY_NAME)
      artifact_feed: presidio
      pypi_extra_index_url: $(PYPI_INDEX_URL)

