queue:
  name: Hosted Ubuntu 1604
steps:
- task: Docker@2
  displayName: 'Build and Push'
  inputs:
    containerRegistry: $(registry)
    repository: $(repository)
    Dockerfile: $(dockerfile)
    tags: |
     $(Build.BuildId)
     latest
trigger:
  batch: true # batch changes if true, start a new build for every push if false
  branches:
    include: $(branch)
  paths:
    include: $(include) # file paths which must match to trigger a build