trigger: # Build triggers
    batch: true # batch changes if true, start a new build for every push if false
    branches:
      include:  # branch names which will trigger a build
        - development
    paths:
      include: # file paths which must match to trigger a build
        - /Dockerfile.python.deps
        - /presidio-analyzer/requirements.txt

jobs: # A job is a collection of steps to be run by an agent 
- job: BuildPythonDeps
  timeoutInMinutes: 120 # how long to run the job before automatically cancelling
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Docker@2
    displayName: 'Build and Push'
    inputs:
      containerRegistry: $(registry) # input registry name
      repository: presidio-python-deps # name of image to build
      Dockerfile: Dockerfile.python.deps # dockerfile path
      tags: | # image tags
        $(Build.BuildId)
        latest