apiVersion: v1
kind: Service
metadata:
  name: client-lb-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081