nlp_engine_name: spacy
models:
  -
    lang_code: en
    model_name: en_core_web_lg
  -
    lang_code: de
    model_name: de_core_news_md
  -
    lang_code: es
    model_name: es_core_news_md
ner_model_configuration:
  model_to_presidio_entity_mapping:
    PER: PERSON
    PERSON: PERSON
    LOC: LOCATION
    LOCATION: LOCATION
    GPE: LOCATION
    ORG: ORGANIZATION
    DATE: DATE_TIME
    TIME: DATE_TIME
    NORP: NRP

  low_confidence_score_multiplier: 0.4
  low_score_entity_names:
    - ORGANIZATION
    - ORG
  default_score: 0.85
