apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "presidium.fullname" . }}-anonymizer
  labels:
    app: {{ template "presidium.fullname" . }}-anonymizer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "presidium.fullname" . }}-anonymizer
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.anonymizer.registry }}/{{ .Values.anonymizer.name }}:{{ default .Chart.AppVersion .Values.anonymizer.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.anonymizer.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.anonymizer.service.internalPort }}
        env:
          - name: presidium_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GRPC_PORT
            value: {{ .Values.anonymizer.service.internalPort | quote }}
      {{ if .Values.privateRegistry }}imagePullSecrets:
        - name: {{.Values.privateRegistry}}{{ end }}