/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.Presidio.Api;
using Microsoft.Presidio.Model;
using Microsoft.Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Microsoft.Presidio.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyzeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyzeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyzeRequest
        //private AnalyzeRequest instance;

        public AnalyzeRequestTests()
        {
            // TODO uncomment below to create an instance of AnalyzeRequest
            //instance = new AnalyzeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyzeRequest
        /// </summary>
        [Fact]
        public void AnalyzeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyzeRequest
            //Assert.IsType<AnalyzeRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'CorrelationId'
        /// </summary>
        [Fact]
        public void CorrelationIdTest()
        {
            // TODO unit test for the property 'CorrelationId'
        }
        /// <summary>
        /// Test the property 'ScoreThreshold'
        /// </summary>
        [Fact]
        public void ScoreThresholdTest()
        {
            // TODO unit test for the property 'ScoreThreshold'
        }
        /// <summary>
        /// Test the property 'Entities'
        /// </summary>
        [Fact]
        public void EntitiesTest()
        {
            // TODO unit test for the property 'Entities'
        }
        /// <summary>
        /// Test the property 'ReturnDecisionProcess'
        /// </summary>
        [Fact]
        public void ReturnDecisionProcessTest()
        {
            // TODO unit test for the property 'ReturnDecisionProcess'
        }
        /// <summary>
        /// Test the property 'AdHocRecognizers'
        /// </summary>
        [Fact]
        public void AdHocRecognizersTest()
        {
            // TODO unit test for the property 'AdHocRecognizers'
        }

    }

}
