/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.Presidio.Api;
using Microsoft.Presidio.Model;
using Microsoft.Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Microsoft.Presidio.Test.Model
{
    /// <summary>
    ///  Class for testing RecognizerResultWithAnaysisExplanationAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecognizerResultWithAnaysisExplanationAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecognizerResultWithAnaysisExplanationAllOf
        //private RecognizerResultWithAnaysisExplanationAllOf instance;

        public RecognizerResultWithAnaysisExplanationAllOfTests()
        {
            // TODO uncomment below to create an instance of RecognizerResultWithAnaysisExplanationAllOf
            //instance = new RecognizerResultWithAnaysisExplanationAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecognizerResultWithAnaysisExplanationAllOf
        /// </summary>
        [Fact]
        public void RecognizerResultWithAnaysisExplanationAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecognizerResultWithAnaysisExplanationAllOf
            //Assert.IsType<RecognizerResultWithAnaysisExplanationAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'AnalysisExplanation'
        /// </summary>
        [Fact]
        public void AnalysisExplanationTest()
        {
            // TODO unit test for the property 'AnalysisExplanation'
        }

    }

}
