/*
 * Presidio
 *
 * Context aware, pluggable and customizable PII anonymization service for text and images.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: presidio@microsoft.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Microsoft.Presidio.Api;
using Microsoft.Presidio.Model;
using Microsoft.Presidio.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Microsoft.Presidio.Test.Model
{
    /// <summary>
    ///  Class for testing RecognizerResultWithAnaysisExplanation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RecognizerResultWithAnaysisExplanationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RecognizerResultWithAnaysisExplanation
        //private RecognizerResultWithAnaysisExplanation instance;

        public RecognizerResultWithAnaysisExplanationTests()
        {
            // TODO uncomment below to create an instance of RecognizerResultWithAnaysisExplanation
            //instance = new RecognizerResultWithAnaysisExplanation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RecognizerResultWithAnaysisExplanation
        /// </summary>
        [Fact]
        public void RecognizerResultWithAnaysisExplanationInstanceTest()
        {
            // TODO uncomment below to test "IsType" RecognizerResultWithAnaysisExplanation
            //Assert.IsType<RecognizerResultWithAnaysisExplanation>(instance);
        }


        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Fact]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'Score'
        /// </summary>
        [Fact]
        public void ScoreTest()
        {
            // TODO unit test for the property 'Score'
        }
        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Fact]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }
        /// <summary>
        /// Test the property 'AnalysisExplanation'
        /// </summary>
        [Fact]
        public void AnalysisExplanationTest()
        {
            // TODO unit test for the property 'AnalysisExplanation'
        }

    }

}
