FROM python:3.9-windowsservercore

ENV PIP_NO_CACHE_DIR=1
WORKDIR /app

COPY ./pyproject.toml /usr/bin/${NAME}/
COPY ./README.md /usr/bin/${NAME}/
COPY ./VERSION /usr/bin/${NAME}/
RUN pip install --upgrade pip
RUN pip install pdm; pdm install --deploy

COPY . .

EXPOSE ${PORT}
CMD pdm run python app.py
